import "./globals.css";
export const metadata = { title: 'v0-1773056079432-ee8w4', description: 'Generated by v0' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}